// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1666108981);
user_pref("app.update.lastUpdateTime.region-update-timer", 0);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1666108741);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 1666108861);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 1666108771);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.region.update.updated", 1666108715);
user_pref("browser.search.region", "IN");
user_pref("browser.theme.dark-toolbar-theme", false);
user_pref("calendar.list.sortOrder", "2afb83fe-a75f-4aa5-b16d-91d2c2a67e4c");
user_pref("calendar.registry.2afb83fe-a75f-4aa5-b16d-91d2c2a67e4c.calendar-main-in-composite", true);
user_pref("calendar.registry.2afb83fe-a75f-4aa5-b16d-91d2c2a67e4c.disabled", true);
user_pref("calendar.registry.2afb83fe-a75f-4aa5-b16d-91d2c2a67e4c.name", "Home");
user_pref("calendar.registry.2afb83fe-a75f-4aa5-b16d-91d2c2a67e4c.type", "storage");
user_pref("calendar.registry.2afb83fe-a75f-4aa5-b16d-91d2c2a67e4c.uri", "moz-storage-calendar://");
user_pref("calendar.timezone.local", "Asia/Kolkata");
user_pref("calendar.ui.version", 3);
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 1);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1666108723336");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 33);
user_pref("extensions.getAddons.cache.lastUpdate", 1666108981);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.incognito.migrated", true);
user_pref("extensions.lastAppBuildId", "20220628000715");
user_pref("extensions.lastAppVersion", "91.11.0");
user_pref("extensions.lastPlatformVersion", "91.11.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webextensions.uuids", "{\"default-theme@mozilla.org\":\"5757e80d-58d6-49d8-aa47-c822f1ee27c6\",\"google@search.mozilla.org\":\"2db48d88-439b-4d4f-913b-f3e8037bc685\",\"ddg@search.mozilla.org\":\"809ba822-7907-405f-8109-7b8ed5c1142a\",\"amazondotcom@search.mozilla.org\":\"309978a6-72ed-4dd1-a74e-638be3dffe42\",\"wikipedia@search.mozilla.org\":\"fa35381d-c30d-4c13-8be0-43fa89ceb73d\",\"bing@search.mozilla.org\":\"f58a2412-e9bf-4c99-8038-5580edf8bc27\"}");
user_pref("mail.ab_remote_content.migrated", 1);
user_pref("mail.folder.views.version", 1);
user_pref("mail.openMessageBehavior.version", 1);
user_pref("mail.spam.version", 1);
user_pref("mail.ui-rdf.version", 32);
user_pref("mailnews.database.global.datastore.id", "da291799-044b-455b-8bd2-83f7dac4fa0");
user_pref("mailnews.headers.extraAddonHeaders", "autocrypt openpgp");
user_pref("mailnews.quotingPrefs.version", 1);
user_pref("mailnews.start_page_override.mstone", "91.11.0");
user_pref("mailnews.tags.$label1.color", "#FF0000");
user_pref("mailnews.tags.$label1.tag", "Important");
user_pref("mailnews.tags.$label2.color", "#FF9900");
user_pref("mailnews.tags.$label2.tag", "Work");
user_pref("mailnews.tags.$label3.color", "#009900");
user_pref("mailnews.tags.$label3.tag", "Personal");
user_pref("mailnews.tags.$label4.color", "#3333FF");
user_pref("mailnews.tags.$label4.tag", "To Do");
user_pref("mailnews.tags.$label5.color", "#993399");
user_pref("mailnews.tags.$label5.tag", "Later");
user_pref("mailnews.tags.version", 2);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.trr.blocklist_cleanup_done", true);
user_pref("pdfjs.enabledCache.state", true);
user_pref("services.settings.clock_skew_seconds", -6402);
user_pref("services.settings.last_etag", "\"1648185887941\"");
user_pref("services.settings.last_update_seconds", 1666115263);
user_pref("services.settings.thunderbird.hijack-blocklists.last_check", 1666115263);
user_pref("services.settings.thunderbird.search-config.last_check", 1666115263);
user_pref("services.settings.thunderbird.url-classifier-skip-urls.last_check", 1666115263);
user_pref("toolkit.telemetry.cachedClientID", "6f0c2dc4-1cfa-4455-b60a-d7dc62b01815");
user_pref("toolkit.telemetry.previousBuildID", "20220628000715");
